# Generated by Django 5.0 on 2024-09-26 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0002_venta_hora_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
