# Generated by Django 5.0 on 2024-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0003_venta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
