# Generated by Django 5.0 on 2024-10-02 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0004_alter_venta_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='costo_de_producto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
