# Generated by Django 5.0 on 2024-10-02 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0005_productos_costo_de_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='costo_de_producto',
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='costo_de_producto_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Costo fijo de producto'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='costo_de_producto_variable',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Costo variable de producto'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='depreciación_de_producto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='depreciación_de_producto'),
        ),
    ]
