# Generated by Django 5.0 on 2024-10-02 18:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0006_remove_productos_costo_de_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='costo_de_producto_fijo',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='costo_de_producto_variable',
        ),
        migrations.RemoveField(
            model_name='ventaitem',
            name='depreciación_de_producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='costo_de_producto_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Costo fijo de producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='costo_de_producto_variable',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Costo variable de producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='depreciación_de_producto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Depreciación de producto'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_items_products', to='businessmodel.productos'),
        ),
    ]
