# Generated by Django 5.0 on 2024-10-06 19:12

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0007_remove_ventaitem_costo_de_producto_fijo_and_more'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_negocio', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('constitucion', models.CharField(choices=[('LTD', 'Compañía Limitada (LTD)'), ('SA', 'Sociedad Anónima (SA)'), ('SAS', 'Sociedad por Acciones Simplificadas (SAS)'), ('SLL', 'Sociedad Limitada Laboral (SLL)'), ('SL', 'Sociedad Limitada (SL)'), ('SC', 'Sociedad Colectiva (SC)'), ('SENC', 'Sociedad En Comandita (SENC)'), ('OTHER', 'Otros')], max_length=50)),
                ('ruc', models.CharField(max_length=20)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_inicial_facturacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_iniciales_de_ingresos_operativos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_de_accionistas', models.IntegerField()),
                ('valor_accionario_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sistema_version', models.CharField(choices=[('QND-SBA-IT1-v.1.4.1', 'QND-SBA-IT1-v.1.4.1'), ('QND-SBA-IT2-v.1.4.0', 'QND-SBA-IT2-v.1.4.0'), ('QND-SBA-IT1(+A)-v.1.4.0', 'QND-SBA-IT1(+A)-v.1.4.0'), ('QND-SBA-IT2(+A)-v.1.4.0', 'QND-SBA-IT2(+A)-v.1.4.0'), ('QND-SBA-IT2(+A+I+D)-v.1.4.0', 'QND-SBA-IT2(+A+I+D)-v.1.4.0'), ('QND-SBA-IT2(+A+I+D+ML+AI)-v.1.4.0', 'QND-SBA-IT2(+A+I+D+ML+AI)-v.1.4.0')], max_length=50)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
        ),
    ]
