# Generated by Django 5.0 on 2024-10-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0008_businessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzamiento', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
                ('detalle_ventas', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
                ('historial_ventas', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
                ('distribucion_ventas', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
                ('frecuencia_ventas', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
                ('porcion_ventas', models.CharField(choices=[('+A', '+A'), ('+I+D', '+I+D'), ('+ML', '+ML'), ('+AI', '+AI')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='sistema_version',
            field=models.CharField(choices=[('QND-SBA-IT1-v.1.4.1', 'QND-SBA-IT1-v.1.4.1'), ('QND-SBA-IT2-v.1.4.0', 'QND-SBA-IT2-v.1.4.0'), ('QND-SBA-IT1(+A)-v.1.4.0', 'QND-SBA-IT1(+A)-v.1.4.0'), ('QND-SBA-IT2(+A)-v.1.4.0', 'QND-SBA-IT2(+A)-v.1.4.0'), ('QND-SBA-IT2(+A+I+D)-v.1.4.0', 'QND-SBA-IT2(+A+I+D)-v.1.4.0'), ('QND-SBA-IT2(+A+I+D+ML)-v.1.4.0', 'QND-SBA-IT2(+A+I+D+ML)-v.1.4.0'), ('QND-SBA-IT2(+A+I+D+ML+AI)-v.1.4.0', 'QND-SBA-IT2(+A+I+D+ML+AI)-v.1.4.0')], max_length=50),
        ),
    ]
