# Generated by Django 5.0 on 2024-10-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0009_systeminfo_alter_businessinfo_sistema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ruc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
