# Generated by Django 5.0 on 2024-10-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0012_ventaitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_items_venta', to='businessmodel.categoryproduct'),
        ),
    ]
