# Generated by Django 5.0 on 2024-10-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0013_alter_ventaitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='payment_gateway',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank transfer', 'Bank transfer'), ('local Credit Card', 'local Credit Card'), ('local Debit Card', 'local Debit Card'), ('Online Credit Card', 'Online Credit Card'), ('Online Debit Card', 'Online Debit Card')], max_length=50, null=True),
        ),
    ]
