# Generated by Django 5.0 on 2024-10-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessmodel', '0014_venta_payment_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='catgeory',
        ),
    ]
